spring.application.name=API-GATEWAY

server.port=8080

spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/**

spring.cloud.gateway.server.webflux.routes[1].id=policy-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://POLICY-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/policies/**

spring.cloud.gateway.server.webflux.routes[2].id=auth-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/auth/**

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

jwt.secret=B0EA2962E150C854E4CAE41DDA28DE70

